version: 2

# This '.circleci/config' is intended to be used in "upstream-master" branch.

jobs:
  build:
    docker:
      - image: quay.io/rust-lang-ja/circleci:edition-guide
    parallelism: 1
    branches:
      ignore:
        - upstream-master
    steps:
      - run:
          name: Print error and exit
          command: |
            if [ "x_$CIRCLE_BRANCH" != "x_upstream-master" ]; then
              echo "ERROR: Wrong '.circleci/config' for $CIRCLE_BRANCH branch."
              echo "       Please contact the developer (e.g. tatsuya6502) to fix."
              exit 8
            fi
